// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace InfoArc.m.anm.it {
    
    
    /// <remarks/>
    [System.Web.Services.WebServiceBinding(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback generaProgrammatoOperationCompleted;
        
        private System.Threading.SendOrPostCallback StatisticheSAEOperationCompleted;
        
        private System.Threading.SendOrPostCallback CaricaDepositiOperationCompleted;
        
        private System.Threading.SendOrPostCallback LineePerDepOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRubricaAllOperationCompleted;
        
        public WebService1() {
            this.Url = "http://m.anm.it/SeviceCruscottoSae.asmx";
        }
        
        public WebService1(string url) {
            this.Url = url;
        }
        
        public event generaProgrammatoCompletedEventHandler generaProgrammatoCompleted;
        
        public event StatisticheSAECompletedEventHandler StatisticheSAECompleted;
        
        public event CaricaDepositiCompletedEventHandler CaricaDepositiCompleted;
        
        public event LineePerDepCompletedEventHandler LineePerDepCompleted;
        
        public event GetRubricaAllCompletedEventHandler GetRubricaAllCompleted;
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/generaProgrammato", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public VDAPFS[] generaProgrammato(string dep, string linea) {
            object[] results = this.Invoke("generaProgrammato", new object[] {
                        dep,
                        linea});
            return ((VDAPFS[])(results[0]));
        }
        
        public System.IAsyncResult BegingeneraProgrammato(string dep, string linea, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("generaProgrammato", new object[] {
                        dep,
                        linea}, callback, asyncState);
        }
        
        public VDAPFS[] EndgeneraProgrammato(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((VDAPFS[])(results[0]));
        }
        
        public void generaProgrammatoAsync(string dep, string linea) {
            this.generaProgrammatoAsync(dep, linea, null);
        }
        
        public void generaProgrammatoAsync(string dep, string linea, object userState) {
            if ((this.generaProgrammatoOperationCompleted == null)) {
                this.generaProgrammatoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngeneraProgrammatoCompleted);
            }
            this.InvokeAsync("generaProgrammato", new object[] {
                        dep,
                        linea}, this.generaProgrammatoOperationCompleted, userState);
        }
        
        private void OngeneraProgrammatoCompleted(object arg) {
            if ((this.generaProgrammatoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.generaProgrammatoCompleted(this, new generaProgrammatoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StatisticheSAE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public Statistiche StatisticheSAE(string dep, string lin) {
            object[] results = this.Invoke("StatisticheSAE", new object[] {
                        dep,
                        lin});
            return ((Statistiche)(results[0]));
        }
        
        public System.IAsyncResult BeginStatisticheSAE(string dep, string lin, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("StatisticheSAE", new object[] {
                        dep,
                        lin}, callback, asyncState);
        }
        
        public Statistiche EndStatisticheSAE(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Statistiche)(results[0]));
        }
        
        public void StatisticheSAEAsync(string dep, string lin) {
            this.StatisticheSAEAsync(dep, lin, null);
        }
        
        public void StatisticheSAEAsync(string dep, string lin, object userState) {
            if ((this.StatisticheSAEOperationCompleted == null)) {
                this.StatisticheSAEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStatisticheSAECompleted);
            }
            this.InvokeAsync("StatisticheSAE", new object[] {
                        dep,
                        lin}, this.StatisticheSAEOperationCompleted, userState);
        }
        
        private void OnStatisticheSAECompleted(object arg) {
            if ((this.StatisticheSAECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StatisticheSAECompleted(this, new StatisticheSAECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CaricaDepositi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public string[] CaricaDepositi() {
            object[] results = this.Invoke("CaricaDepositi", new object[0]);
            return ((string[])(results[0]));
        }
        
        public System.IAsyncResult BeginCaricaDepositi(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CaricaDepositi", new object[0], callback, asyncState);
        }
        
        public string[] EndCaricaDepositi(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        public void CaricaDepositiAsync() {
            this.CaricaDepositiAsync(null);
        }
        
        public void CaricaDepositiAsync(object userState) {
            if ((this.CaricaDepositiOperationCompleted == null)) {
                this.CaricaDepositiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCaricaDepositiCompleted);
            }
            this.InvokeAsync("CaricaDepositi", new object[0], this.CaricaDepositiOperationCompleted, userState);
        }
        
        private void OnCaricaDepositiCompleted(object arg) {
            if ((this.CaricaDepositiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CaricaDepositiCompleted(this, new CaricaDepositiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LineePerDep", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public string[] LineePerDep(string dep) {
            object[] results = this.Invoke("LineePerDep", new object[] {
                        dep});
            return ((string[])(results[0]));
        }
        
        public System.IAsyncResult BeginLineePerDep(string dep, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LineePerDep", new object[] {
                        dep}, callback, asyncState);
        }
        
        public string[] EndLineePerDep(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        public void LineePerDepAsync(string dep) {
            this.LineePerDepAsync(dep, null);
        }
        
        public void LineePerDepAsync(string dep, object userState) {
            if ((this.LineePerDepOperationCompleted == null)) {
                this.LineePerDepOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLineePerDepCompleted);
            }
            this.InvokeAsync("LineePerDep", new object[] {
                        dep}, this.LineePerDepOperationCompleted, userState);
        }
        
        private void OnLineePerDepCompleted(object arg) {
            if ((this.LineePerDepCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LineePerDepCompleted(this, new LineePerDepCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRubricaAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
        public RubricaCell[] GetRubricaAll(string IMEI) {
            object[] results = this.Invoke("GetRubricaAll", new object[] {
                        IMEI});
            return ((RubricaCell[])(results[0]));
        }
        
        public System.IAsyncResult BeginGetRubricaAll(string IMEI, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetRubricaAll", new object[] {
                        IMEI}, callback, asyncState);
        }
        
        public RubricaCell[] EndGetRubricaAll(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RubricaCell[])(results[0]));
        }
        
        public void GetRubricaAllAsync(string IMEI) {
            this.GetRubricaAllAsync(IMEI, null);
        }
        
        public void GetRubricaAllAsync(string IMEI, object userState) {
            if ((this.GetRubricaAllOperationCompleted == null)) {
                this.GetRubricaAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRubricaAllCompleted);
            }
            this.InvokeAsync("GetRubricaAll", new object[] {
                        IMEI}, this.GetRubricaAllOperationCompleted, userState);
        }
        
        private void OnGetRubricaAllCompleted(object arg) {
            if ((this.GetRubricaAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRubricaAllCompleted(this, new GetRubricaAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VDAPFS {
        
        /// <remarks/>
        public string DATAPROG;
        
        /// <remarks/>
        public string RESIDENZATG;
        
        /// <remarks/>
        public string TG;
        
        /// <remarks/>
        public string TM;
        
        /// <remarks/>
        public string AUTISTA;
        
        /// <remarks/>
        public string COGNOME;
        
        /// <remarks/>
        public string NOME;
        
        /// <remarks/>
        public string STR;
        
        /// <remarks/>
        public string BUS;
        
        /// <remarks/>
        public string NOTE;
        
        /// <remarks/>
        public string TMI;
        
        /// <remarks/>
        public string TMF;
        
        /// <remarks/>
        public string TGI;
        
        /// <remarks/>
        public string TGF;
        
        /// <remarks/>
        public string CONVALIDATO;
        
        /// <remarks/>
        public int TURNOSAE;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Statistiche {
        
        /// <remarks/>
        public int P;
        
        /// <remarks/>
        public int MP;
        
        /// <remarks/>
        public int MM;
        
        /// <remarks/>
        public int G;
        
        /// <remarks/>
        public int S;
        
        /// <remarks/>
        public int L;
        
        /// <remarks/>
        public int SAE;
        
        /// <remarks/>
        public int ALTRO;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RubricaCell {
        
        /// <remarks/>
        public string Matricola;
        
        /// <remarks/>
        public string Cognome;
        
        /// <remarks/>
        public string Nome;
        
        /// <remarks/>
        public string Utenza;
    }
    
    public partial class generaProgrammatoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal generaProgrammatoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public VDAPFS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VDAPFS[])(this.results[0]));
            }
        }
    }
    
    public delegate void generaProgrammatoCompletedEventHandler(object sender, generaProgrammatoCompletedEventArgs args);
    
    public partial class StatisticheSAECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StatisticheSAECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Statistiche Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Statistiche)(this.results[0]));
            }
        }
    }
    
    public delegate void StatisticheSAECompletedEventHandler(object sender, StatisticheSAECompletedEventArgs args);
    
    public partial class CaricaDepositiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CaricaDepositiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    public delegate void CaricaDepositiCompletedEventHandler(object sender, CaricaDepositiCompletedEventArgs args);
    
    public partial class LineePerDepCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LineePerDepCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    public delegate void LineePerDepCompletedEventHandler(object sender, LineePerDepCompletedEventArgs args);
    
    public partial class GetRubricaAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRubricaAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public RubricaCell[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RubricaCell[])(this.results[0]));
            }
        }
    }
    
    public delegate void GetRubricaAllCompletedEventHandler(object sender, GetRubricaAllCompletedEventArgs args);
}
